import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { execFileSync } from 'node:child_process';
import { writeIfAbsent, findVaultRoot } from './lib/vault.mjs';

const HERE = path.dirname(url.fileURLToPath(import.meta.url));
const TPL = (name) => fs.readFileSync(path.join(HERE, 'templates', name), 'utf8');

function stepGitignore(v) {
  // FIRST write, always. Merge-safe: append only missing lines.
  const target = path.join(v, '.gitignore');
  const wanted = TPL('gitignore.txt');
  if (!fs.existsSync(target)) { fs.writeFileSync(target, wanted); return 'created'; }
  const have = fs.readFileSync(target, 'utf8');
  const haveLines = new Set(have.split('\n').map(l => l.trim()));
  const add = wanted.split('\n').filter(l => l.trim() && !l.startsWith('#') && !haveLines.has(l.trim()));
  if (add.length) fs.appendFileSync(target, '\n# --- brain-installer additions ---\n' + add.join('\n') + '\n');
  return add.length ? 'merged' : 'present';
}

const CLIENT_BOUNDARY_BODY = 'Client PII boundary. Files under this folder are confidential: never auto-committed to a remote, referenced in index.md/log.md by slug only, never summarized. (see brain schema v1)\n';

function stepTree(v) {
  for (const d of ['raw', 'raw/processed', 'outputs', 'log-archive', '.obsidian']) {
    fs.mkdirSync(path.join(v, d), { recursive: true });
  }
  writeIfAbsent(path.join(v, 'index.md'), '# Index\n\n<!-- one line per Layer-1 page; regenerated by /ingest. Do not hand-edit. -->\n');
  writeIfAbsent(path.join(v, 'log.md'), '# Log\n\n<!-- append-only; monthly rotation to log-archive/ -->\n');
  // layer-1-context/clients/ may not exist yet on a fresh vault (only layer-1-context/ is guaranteed by findVaultRoot).
  fs.mkdirSync(path.join(v, 'layer-1-context', 'clients'), { recursive: true });
  writeIfAbsent(path.join(v, 'layer-1-context', 'clients', '.client-data-boundary'), CLIENT_BOUNDARY_BODY);
  writeIfAbsent(path.join(v, 'outputs', '.client-data-boundary'), CLIENT_BOUNDARY_BODY);
  return 'ok';
}

const START = '<!-- brain-schema:v1:start -->';
const END = '<!-- brain-schema:v1:end -->';

export function upsertSchemaBlock(claudeMdPath, blockBody) {
  const wrapped = `${START}\n${blockBody}\n${END}`;
  let txt = fs.existsSync(claudeMdPath) ? fs.readFileSync(claudeMdPath, 'utf8') : '';
  const re = new RegExp(`${START}[\\s\\S]*?${END}`);
  if (re.test(txt)) {
    fs.writeFileSync(claudeMdPath, txt.replace(re, wrapped));
    return 'replaced';
  }
  const sep = txt.endsWith('\n') ? '\n' : '\n\n';
  fs.writeFileSync(claudeMdPath, txt + sep + wrapped + '\n');
  return 'appended';
}

function stepSchema(v) {
  return upsertSchemaBlock(path.join(v, 'CLAUDE.md'), TPL('schema-block.md').trim());
}

function stepVersion(v) {
  // .brain-version is a marker; rewrite each run (it carries no client content).
  fs.writeFileSync(path.join(v, '.brain-version'),
    JSON.stringify({ schema: 1, installer: '1.0.0', installed: new Date().toISOString() }, null, 2));
  return 'ok';
}

function stepObsidian(v) {
  writeIfAbsent(path.join(v, '.obsidian', 'app.json'), TPL('obsidian-app.json'));
  writeIfAbsent(path.join(v, '.obsidian', 'WEB-CLIPPER-SETUP.md'),
    '# Obsidian Web Clipper\n\nInstall the Obsidian Web Clipper browser extension, then set its **Note location** to `raw/` in this vault.\n\nClips stage into `raw/`; nothing auto-writes. Run `/ingest` to weave them in — that manual step is the review gate (clipped web content is untrusted).\n');
  return 'ok';
}

// Ordered steps. Later tasks push more onto this array BEFORE the default export runs.
export const STEPS = [
  { name: 'gitignore', fn: stepGitignore },
  { name: 'tree', fn: stepTree },
];
STEPS.push({ name: 'schema', fn: stepSchema });
STEPS.push({ name: 'version', fn: stepVersion });
STEPS.push({ name: 'obsidian', fn: stepObsidian });

export function preflight(v) {
  let remote = '';
  try { remote = execFileSync('git', ['remote', '-v'], { cwd: v, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); }
  catch { return { halt: false }; }              // not a git repo → nothing to leak yet
  if (!remote) return { halt: false };
  let tracked = '';
  try { tracked = execFileSync('git', ['ls-files'], { cwd: v, stdio: ['ignore', 'pipe', 'ignore'] }).toString(); } catch { return { halt: false }; }
  const confidential = tracked.split('\n').filter(f =>
    f.includes('layer-1-context/clients/') ||
    (f.endsWith('.md') && (() => {
      try { return /^confidential:\s*true/m.test(fs.readFileSync(path.join(v, f), 'utf8')); }
      catch { return false; }
    })()));
  if (confidential.length) {
    return {
      halt: true,
      reason: `A git remote is configured and ${confidential.length} confidential client file(s) are tracked.`,
      remediation: [
        'DO NOT push. To remediate:',
        '  1. git rm --cached -r layer-1-context/clients/   (keeps local, drops future commits)',
        '  2. Re-run /install-brain (writes .gitignore first).',
        '  3. Scrub history: git filter-repo (or BFG) to purge the files from all commits.',
        '  4. Confirm the remote repo is private (or delete it) until history is clean.',
      ].join('\n'),
    };
  }
  return { halt: false };
}

export function install(vaultRoot, { dryRun = false } = {}) {
  const done = [];
  for (const s of STEPS) {
    if (dryRun) { done.push(`(dry) ${s.name}`); continue; }
    const r = s.fn(vaultRoot);
    done.push(`${s.name}: ${r}`);
  }
  return { steps: done };
}

// CLI entry
if (import.meta.url === url.pathToFileURL(process.argv[1]).href) {
  const args = process.argv.slice(2);
  const vaultArg = args.includes('--vault') ? args[args.indexOf('--vault') + 1] : process.cwd();
  const dryRun = args.includes('--dry-run');
  const root = findVaultRoot(vaultArg);
  if (!root) { console.error('[install-brain] No AI-Brain here (need CLAUDE.md + layer-1-context/). Aborting.'); process.exit(1); }
  const pf = preflight(root);
  if (pf.halt && !args.includes('--force')) {
    console.error('[install-brain] HALT: ' + pf.reason + '\n' + pf.remediation +
      '\n(True PII scrub is manual by design. Re-run with --force only after you understand the above.)');
    process.exit(2);
  }
  const { steps } = install(root, { dryRun });
  console.log('[install-brain] ' + (dryRun ? 'DRY RUN\n' : 'done\n') + steps.map(s => '  · ' + s).join('\n'));
}
